export const ApiResponse = {
  UNKNOWN_NAME: "Le nom d'utilisateur est requis",
  UNKNOWN_EMAIL: "L'adresse mail est requis",
  UNVALID_EMAIL: "L'adresse mail n'est pas valide",
  UNKNOWN_PASSWORD: 'Le mot de passe est requis',
  MINIMAL_PASSWORD_LENGTH: 'Le mot de passe doit avoir au moins 6 caractères',
  DUPLICATE_USER: 'Cet utilisateur existe déjà',
  EMPTY_ID: "L'identifiant est manquant.",
  EMPTY_TOKEN: 'Le token est manquant.',
  NOT_USER: 'Aucun utilisateur trouvé.',
  DUPLICATE_EMAIL: 'Cette adresse email est déjà utilisée.',
  VERIFICATION_EMAIL_SUBJECT: "Vérification de l'adresse mail",
  RESET_PASSWORD_EMAIL_SUBJECT: 'Réinitialisation du mot de passe',
  CHECK_EMAIL_BOX: 'Consulter votre boîte mail.',
  MAIL_ALREADY_VERIFY: "L'adresse mail a déjé été vérifiée.",
  EMAIL_IS_VERIFY: 'Email vérifiée !',
  PASSWORD_CHANGED: 'Mot de passe modifié !',
  EMAIL_CHANGED: 'Email modifié !',
  INCORRECT_PASSWORD: 'Le mot de passe est incorrect !',
};
